source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'nginx'
cookbook 'build-essential'
cookbook 'rbenv', '~> 1.7.1'
cookbook 'rbenv-install-rubies', '~> 0.2.1'
cookbook 'database', '~> 4.0.3'
cookbook 'postgresql', '~> 3.4.18'
cookbook 'redisio', '~> 2.3.0'
cookbook 'rabbitmq', '3.3.0'
cookbook 'openssl'
cookbook 'apache2', '~> 3.1.0'
cookbook 'php', '~> 1.7.2'
cookbook 'mysql', '~> 6.1.2'
cookbook 'mysql2_chef_gem', '~> 1.0.2'